greenlotte6/lotte1-lotteon-project-team1

- src/main/resources/static/style/admin/index.css
- src/main/resources/static/style/common/admin/content.css
- src/main/resources/templates/admin/config/banner/main-top.html
- src/main/resources/templates/admin/config/basic.html
> 배너관리 페이지 화면구현 중

- src/main/resources/static/style/cs/cscommon.css
- src/main/resources/static/style/cs/csmain.css
- src/main/resources/static/style/cs/csnoticelist.css
- src/main/resources/static/style/cs/csnoticeview.css
- src/main/resources/templates/cs/csmain.html
- src/main/resources/templates/cs/csnoticelist.html
- src/main/resources/templates/cs/csnoticeview.html
> main and notice of csservice

- src/main/resources/static/js/admin/config/banner/info.js
- src/main/resources/static/js/admin/config/banner/registry.js
- src/main/resources/static/js/admin/config/version.js
- src/main/resources/static/style/admin/config/banner/main-top.css
- src/main/resources/static/style/admin/config/basic.css
- src/main/resources/static/style/admin/config/category.css
- src/main/resources/static/style/admin/config/policy.css
- src/main/resources/static/style/admin/config/version.css
- src/main/resources/static/style/common/admin/content.css
- src/main/resources/templates/admin/config/banner/main-top.html
- src/main/resources/templates/admin/config/basic.html
- src/main/resources/templates/admin/config/category.html
- src/main/resources/templates/admin/config/policy.html
- src/main/resources/templates/admin/config/version.html
- 약관 관리 및 버전 관리 페이지 화면 구현 완료
- 카테고리 관리 페이지 화면 구현 중
> 약관 관리 및 버전 관리 페이지 화면 구현 완료

- src/main/java/com/example/lotteon/LotteonApplication.java
- src/main/java/com/example/lotteon/controller/admin/AdminMainController.java
- src/main/resources/application.properties
> URL - 컨트롤러 매핑 중

- src/main/resources/static/js/admin/order/orderDetail.js
- src/main/resources/static/js/admin/order/shipment.js
- src/main/resources/static/js/common/admin/modal.mjs
- src/main/resources/static/js/common/admin/registryModal.js
- src/main/resources/static/style/admin/member/point.css
- src/main/resources/static/style/admin/order/order.css
- src/main/resources/static/style/admin/product/product.css
- src/main/resources/static/style/admin/product/register.css
- src/main/resources/static/style/common/admin/content.css
- src/main/resources/templates/admin/member/member.html
- src/main/resources/templates/admin/member/point.html
- src/main/resources/templates/admin/order/order.html
- src/main/resources/templates/admin/product/product.html
- src/main/resources/templates/admin/product/register.html
- src/main/resources/templates/admin/shop/shop.html
- 포인트 관리 페이지 화면 구현 완료
- 주문 관리 페이지 화면 구현 완료
- 상품 관리 페이지 배송 등록 화면 구현 완료
> 주문관리, 포인트관리, 상품관리 페이지 화면구현 완료

- src/main/resources/static/js/common/footer.js
- src/main/resources/static/style/common/header.css
- src/main/resources/static/style/common/policy/policy.css
- src/main/resources/templates/common/header.html
- src/main/resources/templates/common/policy/buyer.html
- src/main/resources/templates/common/policy/finance.html
- src/main/resources/templates/common/policy/location.html
- src/main/resources/templates/common/policy/privacy.html
- src/main/resources/templates/common/policy/seller.html
- src/main/resources/templates/index.html
- 정책 페이지 스타일 및 css/js import 수정
- 푸터 모달 버그 수정 
- 헤더 로고 이미지에 index 링크 추가
> 정책 페이지, 푸터 스타일/버그 수정 및 헤더 로고 링크 추가

- src/main/java/com/example/lotteon/controller/MainController.java
- src/main/java/com/example/lotteon/controller/admin/AdminConfigController.java
- src/main/resources/static/js/admin/config/banner/info.js
- src/main/resources/static/js/admin/config/banner/registry.js
- src/main/resources/static/js/common/footer.js
- src/main/resources/static/style/admin/config/banner/main-top.css
- src/main/resources/templates/admin/config/version.html
- src/main/resources/templates/common/footer.html
- src/main/resources/templates/common/pagination.html
- src/main/resources/templates/index.html
> 인덱스 페이지 매핑

- src/main/resources/static/js/admin/cs/recruit/registry.js
- src/main/resources/static/style/admin/cs/faq/list.css
- src/main/resources/static/style/admin/cs/faq/modify.css
- src/main/resources/static/style/admin/cs/notice/modify.css
- src/main/resources/static/style/admin/cs/notice/write.css
- src/main/resources/static/style/admin/cs/qna/reply.css
- src/main/resources/static/style/admin/cs/qna/view.css
- src/main/resources/static/style/admin/cs/recruit/list.css
- src/main/resources/static/style/common/admin/content.css
- src/main/resources/static/style/index.css
- src/main/resources/templates/admin/cs/faq/list.html
- src/main/resources/templates/admin/cs/faq/modify.html
- src/main/resources/templates/admin/cs/faq/view.html
- src/main/resources/templates/admin/cs/faq/write.html
- src/main/resources/templates/admin/cs/notice/modify.html
- src/main/resources/templates/admin/cs/qna/list.html
- src/main/resources/templates/admin/cs/qna/reply.html
- src/main/resources/templates/admin/cs/qna/view.html
- src/main/resources/templates/admin/cs/qna/write.html
- src/main/resources/templates/admin/cs/recruit/list.html
> 관리자 페이지 화면 구현 완료

- build.gradle
- src/main/java/com/example/lotteon/config/RedisCacheConfig.java
- src/main/java/com/example/lotteon/config/WebMvcConfig.java
- src/main/java/com/example/lotteon/controller/admin/AdminConfigController.java
- src/main/java/com/example/lotteon/controller/api/AdminConfigRestController.java
- src/main/java/com/example/lotteon/entity/admin/config/ConfigDocument.java
- src/main/java/com/example/lotteon/entity/admin/config/CorpInfo.java
- src/main/java/com/example/lotteon/entity/admin/config/CustomerServiceInfo.java
- src/main/java/com/example/lotteon/entity/admin/config/Logo.java
- src/main/java/com/example/lotteon/entity/admin/config/Site.java
- src/main/java/com/example/lotteon/interceptor/ConfigApplicationInterceptor.java
- src/main/java/com/example/lotteon/service/admin/AdminConfigService.java
- src/main/java/com/example/lotteon/service/admin/CacheService.java
- src/main/resources/application.yml
- Spring -MongoDB 연동 및 데이터 I/O 구현
- Redis를 이용한 기본 설정 데이터 캐싱 메커니즘 구현
- 캐시 데이터 활용을 위해서 HTTP 요청을 전처리 하는 Interceptor 구현
> 관리자 기본 설정 기능 구현 90% 완료

- src/main/java/com/example/lotteon/config/WebMvcConfig.java
- src/main/java/com/example/lotteon/controller/MainController.java
- src/main/java/com/example/lotteon/interceptor/AppVersionSetter.java
- src/main/resources/application.yml
- src/main/resources/templates/common/footer.html
- 앱 버전 0.0.4로 업데이트
- 앱 버전 인터셉터 구현 완료
> 앱 버전 업데이트 및 앱 버전 인터셉터 구현

- src/main/java/com/example/lotteon/controller/user/UserController.java
UserController에 빠져 있던 패키지 import
> Imported required packages

- src/main/resources/static/js/admin/config/basic.js
- src/main/resources/templates/common/footer.html
- src/main/resources/templates/index.html
- index.html, footer.html에 설정 데이터 렌더링 완료
- basic.js 리팩터링
> 설정 데이터 렌더링 완료

- src/main/java/com/example/lotteon/config/WebMvcConfig.java
- src/main/java/com/example/lotteon/controller/MainController.java
- src/main/java/com/example/lotteon/interceptor/ConfigApplicationInterceptor.java
- src/main/java/com/example/lotteon/repository/admin/AdminConfigRepository.java
> 캐시 데이터 자동 렌더링 구현

- src/main/java/com/example/lotteon/config/WebMvcConfig.java
- src/main/java/com/example/lotteon/controller/admin/AdminConfigController.java
- src/main/java/com/example/lotteon/controller/api/AdminConfigRestController.java
- src/main/java/com/example/lotteon/entity/admin/config/Logo.java
- src/main/java/com/example/lotteon/interceptor/ConfigApplicationInterceptor.java
- src/main/java/com/example/lotteon/repository/admin/AdminConfigRepository.java
- src/main/java/com/example/lotteon/service/admin/AdminConfigService.java
- src/main/java/com/example/lotteon/service/admin/CacheService.java
- src/main/resources/application.yml
- src/main/resources/static/js/admin/config/basic.js
- src/main/resources/static/js/admin/config/upload.js
- src/main/resources/templates/admin/config/basic.html
- src/main/resources/templates/common/admin/header.html
- src/main/resources/templates/common/footer.html
- src/main/resources/templates/common/header.html
- src/main/resources/templates/index.html
- 관리자 기본 설정 이미지 업로드 및 전체 페이지 적용 구현 완료
> 관리자 기본 설정 기능 구현 완료

- src/main/resources/application.yml
> modified production mongodb url

- Dockerfile
- src/main/resources/application.yml
> 도커파일 수정 및 배포환경 업로드 경로 수정

- src/main/resources/templates/common/policy/_termsMenu.html
- src/main/resources/templates/common/policy/buyer.html
- src/main/resources/templates/common/policy/finance.html
- src/main/resources/templates/common/policy/location.html
- src/main/resources/templates/common/policy/privacy.html
- src/main/resources/templates/common/policy/seller.html
> 정책 페이지 에러 및 버그 수정

- src/main/java/com/example/lotteon/controller/api/AdminConfigRestController.java
> modified response body

- database/dummy.sql
- src/main/java/com/example/lotteon/controller/admin/seller/AdminSellerController.java
- src/main/java/com/example/lotteon/controller/api/AdminSellerApiController.java
- src/main/java/com/example/lotteon/controller/user/UserController.java
- src/main/java/com/example/lotteon/dto/product/ProductDTO.java
- src/main/java/com/example/lotteon/dto/product/ProductOptionsDTO.java
- src/main/java/com/example/lotteon/dto/seller/SellerDTO.java
- src/main/java/com/example/lotteon/dto/seller/SellerIdDTO.java
- src/main/java/com/example/lotteon/dto/user/UserDTO.java
- src/main/java/com/example/lotteon/entity/product/ProductOptions.java
- src/main/java/com/example/lotteon/entity/seller/Seller.java
- src/main/java/com/example/lotteon/entity/seller/SellerCompositeKey.java
- src/main/java/com/example/lotteon/exception/EntityAlreadyExistsException.java
- src/main/java/com/example/lotteon/repository/order/OrderRepositoryImpl.java
- src/main/java/com/example/lotteon/repository/seller/CustomSellerRepository.java
- src/main/java/com/example/lotteon/repository/seller/CustomSellerRepositoryImpl.java
- src/main/java/com/example/lotteon/repository/seller/SellerRepository.java
- src/main/java/com/example/lotteon/service/seller/SellerService.java
- src/main/java/com/example/lotteon/service/user/UserService.java
- src/main/resources/application.yml
- src/main/resources/static/js/admin/seller/delete.js
- src/main/resources/static/js/admin/seller/updateStatus.js
- src/main/resources/static/js/common/admin/checkbox.js
- src/main/resources/static/style/admin/shop/shop.css
- src/main/resources/static/style/common/pagination.css
- src/main/resources/templates/admin/shop/shop.html
- src/main/resources/templates/common/pagination.html
- 상점 등록, 삭제, 검색, 상태 변경 기능 구현 완료
- 매출 현황 기능은 상품, 주문, 배송 관리 기능 구현 완료 후 구현 예정
> 관리자 상점 관리 기능 구현 완료

- src/main/java/com/example/lotteon/controller/admin/member/MemberManagementController.java
- src/main/java/com/example/lotteon/controller/api/MemberManagementApiController.java
- src/main/java/com/example/lotteon/repository/user/MemberRepositoryCustom.java
- src/main/java/com/example/lotteon/repository/user/MemberRepositoryImpl.java
- src/main/java/com/example/lotteon/service/user/MemberService.java
- src/main/resources/static/js/admin/member/onModalOpen.js
- src/main/resources/static/js/admin/member/updateLevel.js
- src/main/resources/static/js/admin/member/updateStatus.js
- src/main/resources/templates/admin/member/member.html
> 회원 관리 페이지 기능구현 완료

- src/main/java/com/example/lotteon/config/ApplicationConfig.java
- src/main/java/com/example/lotteon/controller/admin/coupon/AdminCouponController.java
- src/main/java/com/example/lotteon/dto/PageRequestDTO.java
- src/main/java/com/example/lotteon/dto/PageResponseDTO.java
- src/main/java/com/example/lotteon/dto/coupon/CouponDTO.java
- src/main/java/com/example/lotteon/entity/coupon/Coupon.java
- src/main/java/com/example/lotteon/entity/coupon/Coupon_Benefit.java
- src/main/java/com/example/lotteon/repository/coupon/CouponRepository.java
- src/main/java/com/example/lotteon/repository/coupon/custom/CouponRepositoryCustom.java
- src/main/java/com/example/lotteon/repository/coupon/impl/CouponRepositoryImpl.java
- src/main/java/com/example/lotteon/service/coupon/CouponService.java
- src/main/resources/static/js/admin/coupon/coupon.js
- src/main/resources/templates/admin/coupon/coupon.html
> coupon 상세정보까지 완료

- src/main/java/com/example/lotteon/controller/admin/coupon/AdminCouponController.java
- src/main/java/com/example/lotteon/dto/PageRequestDTO.java
- src/main/java/com/example/lotteon/dto/PageResponseDTO.java
- src/main/java/com/example/lotteon/dto/coupon/Coupon_HistoryDTO.java
- src/main/java/com/example/lotteon/repository/coupon/CouponHistoryRepository.java
- src/main/java/com/example/lotteon/repository/coupon/CouponRepository.java
- src/main/java/com/example/lotteon/repository/coupon/custom/CouponHistoryRepositoryCustom.java
- src/main/java/com/example/lotteon/repository/coupon/custom/CouponRepositoryCustom.java
- src/main/java/com/example/lotteon/repository/coupon/impl/CouponHistoryRepositoryImpl.java
- src/main/java/com/example/lotteon/repository/coupon/impl/CouponRepositoryImpl.java
- src/main/java/com/example/lotteon/service/coupon/CouponHistoryService.java
- src/main/java/com/example/lotteon/service/coupon/CouponService.java
- src/main/java/com/example/lotteon/service/user/MemberService.java
- src/main/resources/static/js/admin/coupon/coupon.js
- src/main/resources/templates/admin/coupon/issued.html
- src/main/resources/templates/admin/coupon/searchcoupon.html
- src/main/resources/templates/common/admin/aside.html
> 회원가입 시 쿠폰 뿌리기

- src/main/resources/application.yml
> Added a property for jpa

- .github/workflows/cicd.yml
Changed docker run port forwarding option
> Changed docker run port forwarding option

- src/main/java/com/example/lotteon/controller/admin/coupon/AdminCouponController.java
- src/main/java/com/example/lotteon/service/coupon/CouponHistoryService.java
- src/main/resources/static/js/admin/coupon/couponHistory.js
- src/main/resources/templates/admin/coupon/issued.html
> 쿠폰 발급현황 정보 보기

- src/main/java/com/example/lotteon/config/ApplicationConfig.java
- src/main/java/com/example/lotteon/controller/admin/coupon/AdminCouponController.java
- src/main/java/com/example/lotteon/service/coupon/CouponHistoryService.java
- src/main/resources/static/js/admin/coupon/couponHistory.js
- src/main/resources/templates/admin/coupon/issued.html
> 쿠폰 발급이력 상세보기 및 중단 버튼 활성화

- src/main/java/com/example/lotteon/controller/mypage/MypageMain.java
- src/main/java/com/example/lotteon/controller/product/ProductDetail.java
- src/main/java/com/example/lotteon/controller/user/UserController.java
- src/main/java/com/example/lotteon/service/admin/CacheService.java
- src/main/java/com/example/lotteon/service/mypage/MyPageService.java
- src/main/java/com/example/lotteon/service/user/MemberService.java
- src/main/resources/static/js/mypage/mypagevalidation.js
- src/main/resources/static/style/common/myPage/confirmPassword.css
- src/main/resources/templates/myPage/confirmPassword.html
- src/main/resources/templates/myPage/setting.html
- src/main/resources/templates/user/terms.html
> 마이페이지 나의 설정

- src/main/java/com/example/lotteon/controller/mypage/MypageMain.java
- src/main/java/com/example/lotteon/entity/user/Member.java
- src/main/java/com/example/lotteon/repository/user/MemberRepository.java
- src/main/java/com/example/lotteon/service/mypage/MyPageService.java
- src/main/resources/templates/myPage/setting.html
> mypage 회원탈퇴 구현중

- src/main/java/com/example/lotteon/security/MyUserDetailsService.java
- src/main/java/com/example/lotteon/service/mypage/MyPageService.java
> 마이페이지 회원탈퇴 수정 

- src/main/java/com/example/lotteon/controller/admin/config/BasicConfigController.java
- src/main/java/com/example/lotteon/dto/admin/PolicyDTO.java
- src/main/java/com/example/lotteon/entity/admin/config/Policy.java
- src/main/java/com/example/lotteon/repository/admin/config/PolicyRepository.java
- src/main/java/com/example/lotteon/service/admin/PolicyService.java
- src/main/resources/templates/admin/config/policy.html
- src/main/resources/templates/admin/config/version.html
- src/main/resources/templates/common/admin/footer.html
> 약관 관리 기능 구현 완료

- src/main/java/com/example/lotteon/controller/mypage/MypageMain.java
- src/main/java/com/example/lotteon/repository/cs/QnaRepository.java
- src/main/java/com/example/lotteon/service/cs/QnaService.java
- src/main/resources/templates/myPage/qna.html
> 마이페이지 문의하기 

- src/main/java/com/example/lotteon/controller/api/VersionConfigRestController.java
- src/main/java/com/example/lotteon/entity/admin/config/VersionConfig.java
- src/main/java/com/example/lotteon/repository/admin/config/BasicConfigRepository.java
- src/main/java/com/example/lotteon/service/admin/BasicConfigService.java
- src/main/resources/static/js/admin/config/version.js
- src/main/resources/templates/admin/config/version.html
> 버전 관리 삭제 기능 구현 완료

- src/main/java/com/example/lotteon/controller/mypage/MypageMain.java
- src/main/java/com/example/lotteon/repository/admin/point/PointRepository.java
- src/main/java/com/example/lotteon/repository/coupon/CouponHistoryRepository.java
- src/main/java/com/example/lotteon/repository/cs/QnaRepository.java
- src/main/java/com/example/lotteon/service/admin/point/PointService.java
- src/main/java/com/example/lotteon/service/coupon/CouponHistoryService.java
- src/main/java/com/example/lotteon/service/cs/QnaService.java
- src/main/resources/static/style/common/cspagination.css
- src/main/resources/templates/myPage/coupon.html
- src/main/resources/templates/myPage/point.html
- src/main/resources/templates/myPage/qna.html
> 마이페이지 쿠폰 포인트

- src/main/java/com/example/lotteon/controller/product/CartController.java
- src/main/resources/application.yml
- 세션에서 장바구니 상품을 제거하지 않아 발생하는 버그 수정
- application.yml 버전 업데이트
> 장바구니 버그 수정 및 버전 업데이트

- src/main/java/com/example/lotteon/controller/order/OrderController.java
- src/main/java/com/example/lotteon/controller/product/CartController.java
- src/main/java/com/example/lotteon/service/product/CartService.java
- src/main/resources/templates/admin/order/order.html
- src/main/resources/templates/common/admin/aside.html
- src/main/resources/templates/common/admin/header.html
- src/main/resources/templates/product/proOrder.html
- src/main/resources/templates/product/shoppingCart.html
- 상품 상세 > 주문하기 기능 구현 완료
- 장바구니 > 주문하기 기능 구현 완료
> 주문 기능 구현 완료

- src/main/java/com/example/lotteon/dto/order/MypageOrderWrapper.java
- src/main/java/com/example/lotteon/repository/order/OrderRepositoryImpl.java
- src/main/resources/templates/myPage/wholeorder.html
> 마이페이지 전체주문내역

- src/main/java/com/example/lotteon/controller/admin/config/BasicConfigController.java
- src/main/java/com/example/lotteon/controller/admin/product/ProductManagementController.java
- src/main/java/com/example/lotteon/dto/product/ProductCategoryDTO.java
- src/main/java/com/example/lotteon/dto/product/ProductSubCategoryDTO.java
- src/main/java/com/example/lotteon/service/admin/CacheService.java
- src/main/java/com/example/lotteon/service/product/category/ProductCategoryService.java
- src/main/java/com/example/lotteon/service/product/category/ProductSubCategoryService.java
Redis Cache를 이용한 카테고리 캐싱 기능 구현 완료
> 카테고리 캐싱 기능 구현 완료

- src/main/java/com/example/lotteon/controller/mypage/MypageMain.java
- src/main/java/com/example/lotteon/repository/order/OrderRepositoryCustom.java
- src/main/java/com/example/lotteon/repository/order/OrderRepositoryImpl.java
- src/main/java/com/example/lotteon/service/mypage/MyPageService.java
- src/main/resources/static/js/mypage/order-info-modal.js
- src/main/resources/static/js/mypage/seller-info-modal.js
- src/main/resources/static/style/common/myPage/modal/inquiry-modal.css
- src/main/resources/static/style/common/myPage/modal/order-modal.css
- src/main/resources/static/style/common/myPage/modal/seller-modal.css
- src/main/resources/templates/myPage/mypageMain.html
- src/main/resources/templates/myPage/wholeorder.html
> 마이페이지 상세정보 모달

- src/main/java/com/example/lotteon/config/ApplicationConfig.java
- src/main/java/com/example/lotteon/config/LocalDateTimeAdapter.java
- src/main/java/com/example/lotteon/config/WebMvcConfig.java
- src/main/java/com/example/lotteon/controller/MainController.java
- src/main/java/com/example/lotteon/controller/admin/config/BasicConfigController.java
- src/main/java/com/example/lotteon/controller/user/UserController.java
- src/main/java/com/example/lotteon/entity/admin/banner/BannerInfo.java
- src/main/java/com/example/lotteon/repository/admin/config/BannerRepository.java
- src/main/java/com/example/lotteon/service/admin/CacheService.java
- src/main/resources/application.yml
- src/main/resources/static/style/admin/config/banner/main-top.css
- src/main/resources/static/style/index.css
- src/main/resources/static/style/user/login.css
- src/main/resources/templates/admin/config/banner/login.html
- src/main/resources/templates/admin/config/banner/main-slider.html
- src/main/resources/templates/admin/config/banner/mypage.html
- src/main/resources/templates/admin/config/banner/product-detail.html
- src/main/resources/templates/index.html
- src/main/resources/templates/user/login.html
> 배너 관리 기능 및 캐싱 구현 완료

- src/main/java/com/example/lotteon/controller/admin/AdminMainController.java
- src/main/java/com/example/lotteon/dto/admin/StatisticDTO.java
- src/main/java/com/example/lotteon/repository/cs/custom/NoticeRepositoryCustom.java
- src/main/java/com/example/lotteon/repository/cs/custom/QnaRepositoryCustom.java
- src/main/java/com/example/lotteon/repository/cs/impl/NoticeRepositoryImpl.java
- src/main/java/com/example/lotteon/repository/cs/impl/QnaRepositoryImpl.java
- src/main/java/com/example/lotteon/repository/order/OrderRepositoryCustom.java
- src/main/java/com/example/lotteon/repository/order/OrderRepositoryImpl.java
- src/main/java/com/example/lotteon/service/admin/statistics/StatisticsService.java
- src/main/java/com/example/lotteon/service/cs/CsService.java
- src/main/java/com/example/lotteon/service/cs/QnaService.java
- src/main/java/com/example/lotteon/service/order/OrderService.java
- src/main/resources/templates/admin/index.html
> 관리자 메인 페이지 구현중

- src/main/java/com/example/lotteon/controller/mypage/MypageMain.java
- src/main/java/com/example/lotteon/dto/order/MypageOrderWrapper.java
- src/main/java/com/example/lotteon/entity/order/Order.java
- src/main/java/com/example/lotteon/repository/order/OrderRepositoryImpl.java
- src/main/java/com/example/lotteon/repository/seller/SellerRepository.java
- src/main/java/com/example/lotteon/service/cs/QnaService.java
- src/main/java/com/example/lotteon/service/mypage/MyPageService.java
- src/main/resources/static/js/mypage/confirm-info-modal.js
- src/main/resources/static/js/mypage/order-info-modal.js
- src/main/resources/static/js/mypage/seller-info-modal.js
- src/main/resources/templates/myPage/wholeorder.html
> 마이페이지 구매확정까지 완료

- Dockerfile
- src/main/java/com/example/lotteon/controller/admin/AdminMainController.java
- src/main/java/com/example/lotteon/repository/UserRepository.java
- src/main/java/com/example/lotteon/repository/cs/custom/QnaRepositoryCustom.java
- src/main/java/com/example/lotteon/repository/cs/impl/QnaRepositoryImpl.java
- src/main/java/com/example/lotteon/repository/user/CustomUserRepository.java
- src/main/java/com/example/lotteon/repository/user/CustomUserRepositoryImpl.java
- src/main/java/com/example/lotteon/service/admin/statistics/StatisticsService.java
> 관리자 메인 기능 구현 중

- src/main/java/com/example/lotteon/advice/GlobalModelAttributeAdvice.java
- src/main/java/com/example/lotteon/repository/jpa/product/ProductRepository.java
- src/main/resources/application.yml
> Fixed import error

- src/main/resources/application.yml
> Fixed indentation

- .github/workflows/cicd.yml
- Dockerfile
- src/main/java/com/example/lotteon/controller/admin/product/ProductManagementController.java
> 도커 볼륨 커맨드 수정

- src/main/java/com/example/lotteon/controller/mypage/MypageMain.java
- src/main/java/com/example/lotteon/dto/order/ReturnDTO.java
- src/main/java/com/example/lotteon/dto/order/ReturnImageDTO.java
- src/main/java/com/example/lotteon/dto/order/ReturnReasonDTO.java
- src/main/java/com/example/lotteon/entity/order/Return.java
- src/main/java/com/example/lotteon/entity/order/ReturnImage.java
- src/main/java/com/example/lotteon/entity/order/ReturnReason.java
- src/main/java/com/example/lotteon/repository/jpa/order/ReturnRepository.java
- src/main/java/com/example/lotteon/service/mypage/MyPageService.java
- src/main/resources/static/js/mypage/exchange-info-modal.js
- src/main/resources/static/js/mypage/return-info-modal.js
- src/main/resources/static/style/common/myPage/modal/exchange-modal.css
- src/main/resources/templates/myPage/mypageMain.html
- src/main/resources/templates/myPage/review.html
- src/main/resources/templates/myPage/wholeorder.html
> Conflict resolved

- src/main/java/com/example/lotteon/controller/mypage/MypageMain.java
- src/main/java/com/example/lotteon/dto/order/ReturnDTO.java
- src/main/java/com/example/lotteon/dto/order/ReturnImageDTO.java
- src/main/java/com/example/lotteon/dto/order/ReturnReasonDTO.java
- src/main/java/com/example/lotteon/entity/order/Return.java
- src/main/java/com/example/lotteon/entity/order/ReturnImage.java
- src/main/java/com/example/lotteon/entity/order/ReturnReason.java
- src/main/java/com/example/lotteon/repository/order/ReturnRepository.java
- src/main/java/com/example/lotteon/service/mypage/MyPageService.java
- src/main/resources/application.yml
- src/main/resources/static/js/mypage/exchange-info-modal.js
- src/main/resources/static/js/mypage/return-info-modal.js
- src/main/resources/static/style/common/myPage/modal/exchange-modal.css
- src/main/resources/templates/myPage/mypageMain.html
- src/main/resources/templates/myPage/review.html
- src/main/resources/templates/myPage/wholeorder.html
> 마이페이지 메인 및 로그인 설정
